id: getting_started_tooljet
learningObjectives:
  - Familiarize yourself with the ToolJet platform and its interface.
hints:
  - Check out ToolJet's documentation [here](https://docs.tooljet.com).
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text:
              ToolJet is a no-code development platform where you can drag and drop
              components to build applications.
          - text:
              ToolJet’s key features include a visual builder, integrations with popular
              APIs, and deployment tools.
          - text: If you don't have a ToolJet account yet, don't worry! You can easily create one [here](https://www.tooljet.com/login) and start building amazing applications in no time.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step
